### PR TITLE
Renaming a cloned part now renames all of its clones, + compile fixes

### PR DESCRIPTION
**Pull request by ViktorNova**
This partially addresses https://github.com/falkTX/los/issues/18
When a cloned part is renamed, all of it's clones are now traversed and subsequently renamed also. 
(I'm working on getting colors to behave the same way but am not quite there yet)

Also, I removed the -j4 flag from the build script compile_los.sh, as this seemed to make the build process get ahead of itself and break. (if the old script was ran multiple times, it would eventually build, but with -j4 removed it now successfully builds the first time)

### CODE REVIEW

**Comment by falkTX** [comment]
Thanks! Glad to see some interest on the project.

I don't want to limit your changes by having to do PR each time.
So I'm adding you as collaborator for this project. :)

**Comment by ViktorNova** [comment]
Thanks a bunch Filipe! It's an honor, I won't let you down.

I seriously love this sequencer, it fills a void in the Linux audio world that isn't quite met by anything else (including MusE.. even though they share an old codebase, I find LOS to be much faster and more stable, not to mention looking a lot better)

I'll continue to add little improvements here and there, I'd really like to see LOS brought up to speed and get some traction, I think a lot of people would use it if it were out there a little more. =) 

Have you considered adding it to your KXStudio repositories?

**Comment by falkTX** [comment]
los is already in the testing repository.
but I don't want real public usage at least until the transition from openoctave is complete.

there's quite a few things that still need change regarding the theme, styling and artwork.
but tbh I use it myself everytime I need to do some quick midi stuff.
I'm fine with it being more of an internal thing for now. Less pressure to add new features and just enjoy what works in my own pace. Maybe it's the same for you too.

**Comment by ViktorNova** [comment]
I understand that, I kind of feel the same way about it. 

If you add some of the things you'd like to see brought up to speed to the issues here, I would be happy to take a stab at some of them that are within my skillset (which is mostly limited to UI things anyhow =)

I did not know it was in your testing repo! That is excellent news.

**Pull request merged**
